clusters:
  - project: project-x
    groupRbac: "la-demos:g-gitops"
    argocd: "enabled"
    nodePools:
      - isolated: true
  - project: project-y
    groupRbac: "la-demos:g-gitops-2"
    argocd: "disabled"
    nodePools:
      - isolated: false