apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    argocd.argoproj.io/instance: controlplane-argocd
  name: external-dns
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          external-dns: enabled
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;..
      name: '{{name}}-external-dns'
    spec:
      destination:
        name: '{{name}}'
        namespace: external-dns
      ignoreDifferences:
      - group: apps
        jsonPointers:
        - /spec/replicas
        kind: Deployment
      - group: apps
        jsonPointers:
        - /spec/replicas
        kind: StatefulSet
      project: default
      sources:
      - ref: valuesRepo
        repoURL: https://github.com/la-cc/demos.git
        targetRevision: main
      - helm:
          ignoreMissingValueFiles: true
          releaseName: external-dns
          valueFiles:
          - values.yaml
          - $valuesRepo/guest-lecture-platform-engineering-org-2025-how-to-build-a-multitenancy-internal-developer-platform/customer-service-catalog/helm/{{name}}/external-dns/values.yaml
        path: guest-lecture-platform-engineering-org-2025-how-to-build-a-multitenancy-internal-developer-platform/managed-service-catalog/helm/external-dns
        repoURL: https://github.com/la-cc/demos.git
        targetRevision: main
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=false
        - PruneLast=true
        - FailOnSharedResource=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true