argo-cd:
  dex:
    enabled: false
  global:
    tolerations:
      - key: "project"
        operator: "Equal"
        value: "project-x"
        effect: "NoSchedule"
    nodeSelector:
      project: "project-x"
    domain: argocd.vcluster-project-x.platformcon.stackit.run
    imagePullSecrets:
      - name: image-pull-secret
    revisionHistoryLimit: 5
  server:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      enabled: true
      ingressClassName: nginx
      tls: true